### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by HaoZeke** [coolshou/purple-line#3]
The steps were:
git clone
cd DIR
make
The error was
make -C libpurple
make[1]: Entering directory '/home/haozeke/Github/Pidgin/LINE/purple-line/libpurple'
mkdir -p thrift_line
thrift --gen cpp -out thrift_line line.thrift
make[1]: thrift: Command not found
make[1]: **\* No rule to make target 'thrift_line/line_constants.o', needed by 'libline.so'.  Stop.
make[1]: Leaving directory '/home/haozeke/Github/Pidgin/LINE/purple-line/libpurple'
Makefile:2: recipe for target 'all' failed
make: **\* [all] Error 2

Any help would be appreciated

**Comment by coolshou** [comment]
You need to install thrift-compiler

which can be download from https://thrift.apache.org/
v0.9.2 is ok

**Comment by HaoZeke** [comment]
Thanks, working great...
